# Makefile for tsg library
# ========================
# by R.J.Barnes
#

INCLUDE=-I$(IPATH)/superdarn

SRC  = maketsg.c checktsg.c
OBJS = maketsg.o checktsg.o
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = tsg
include $(MAKELIB)








 

 















