# Makefile for make_rawinx
# ========================
# Author: R.J.Barnes
# by R.J.Barnes
#
#

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
OBJS = make_iqinx.o
SRC=hlpstr.h errstr.h make_iqinx.c
OUTPUT = $(BINPATH)/make_iqinx
LIBS=-liqdata.1 -lopt.1 -lrcnv.1 -ldmap.1 -lrtime.1
SLIB=-lm
include $(MAKEBIN)
 

